### ISSUE TITLE
Strange results when using SELECT in a function

### ISSUE THREAD

**Issue by bloggy** [Govindass/skript-db#5] opened 2021-04-05 13:45 UTC
I get `<none>` on the first run and the correct value on the second run of my script, which is very strange. Maybe you can tell me what's happening here. 
A broadcast within the function will always display the correct value on the first run.
With first run and second run I mean entering the command "/test".

**Versions:**
- This server is running Tuinity version git-Tuinity-"94f025a" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
- Loading Skript v2.5.3
- [skript-db] Loading skript-db v1.2.1
- 

**The script:**

```
function testing(p: player) :: number:
	set {_uuid} to {_p}'s uuid
	execute "SELECT uuid, player, points FROM `mytable` WHERE `uuid` = %{_uuid}%;" in {sql} and store the result in {_r::*}
	set {_points} to {_r::points::1}
	# This will return the correct value!
	#broadcast "Points: %{_points}%"
	return {_points}


command /test:
	trigger:
		set {_p} to the player
		set {_result} to testing({_p})
		# This will return the wrong value (it will return <none> on the first run, and the correct value on the second run)!
		message "Final: %{_result}%"
```

**Table Structure (Screenshot):**
https://i.imgur.com/p9Vh15W.png

How can this happen? How to fix?

**Comment by Govindass** [comment] 2021-04-05 13:46
it is because you cannot use delayed effects in functions, execute is delayed

**Comment by ham1255** [comment] 2021-04-05 13:47
why is it *delayed execute*

**Comment by ham1255** [comment] 2021-04-05 13:48
Why execution is delayed here?

**Comment by bloggy** [comment] 2021-04-05 13:49
Thank you for your quick reply. 
Same question: 
- Why would execute be delayed? Reason for this?
- What would be the best to fix it?

**Comment by Govindass** [comment] 2021-04-05 13:49
> Thank you for your quick reply.
> Same question:
> 
>     * Why would execute be delayed? Reason for this?
> 
>     * What would be the best to fix it?

it is delayed to not lag the server, the queries are ran on separate thread

**Comment by Govindass** [comment] 2021-04-05 13:50
in future version I will make "synchronous execute" to also be asynchronous, but converting the current code to async, thus avoiding delay, so maybe that'll be able to solve the issue partially

**Comment by bloggy** [comment] 2021-04-05 13:53
So that means for now I am unable to use return values that come from SELECT statements in a skript function?

**Comment by Govindass** [comment] 2021-04-05 13:57
yes, that's the case with all similar add-ons, a workaround is skript-reflect's delayed effect

**Comment by bloggy** [comment] 2021-04-05 14:02
And what about this situation:

Can it happen that when I send two EXECUTE commands one right after the other, the result of the second event is not displayed correctly to me?

Example:
```
execute "INSERT INTO {@table} (`uuid`, `player`, `points`) VALUES (%{_uuid}%, %{_playername}%, %{_points}%) ON DUPLICATE KEY UPDATE `player` = %{_playername}%, `points` = %{_points}%" in {sql}
execute "SELECT uuid, player, points FROM `{@table}` WHERE `uuid` = %{_uuid}%;" in {sql} and store the result in {_r::*}
```

Could the SELECT result then be empty the first time because the INSERT INTO wasn't fast enough for the SELECT to receive the new value?

Regarding skript-reflect's delayed effect: it may be inconsistend as well, or not? Because you never know how long to wait?

**Comment by Govindass** [comment] 2021-04-05 14:03
it should be consistent and shouldn't have any issues, mysql should handle it well

you know how long to wait, wait until a value is returned

**Comment by bloggy** [comment] 2021-04-05 14:04
Could you by any chance post an example of such a skript-reflect "delay" syntax?

**Comment by Govindass** [comment] 2021-04-05 14:05
sadly I do not have an example, but if I remember correctly, you just type:
```delay the effect``` or something like that

**Comment by Govindass** [comment] 2021-04-12 13:30
I am closing this issue as this is intended and not a bug

**Closed by Govindass** 2021-04-12 13:30 UTC
