### ISSUE TITLE
Cannot load plugins/skript-db/config.yml

### ISSUE THREAD

**Issue by toonystank** [Govindass/skript-db#8] opened 2021-04-19 06:25 UTC
[06:20:56 ERROR]: Cannot load plugins/skript-db/config.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
 in 'string', line 6, column 1:
    sql-driver-class-name:"default"
    ^
could not find expected ':'
 in 'string', line 7, column 1:
    
    ^

        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:157) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:133) ~[patched_1.16.5.jar:git-Purpur-1057]
        at com.btk5h.skriptdb.skript.EffExecuteStatement.<clinit>(EffExecuteStatement.java:54) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at ch.njol.skript.SkriptAddon.loadClasses(SkriptAddon.java:107) ~[?:?]
        at com.btk5h.skriptdb.SkriptDB.onEnable(SkriptDB.java:105) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1057]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:582) ~[patched_1.16.5.jar:git-Purpur-1057]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1057]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1060) ~[patched_1.16.5.jar:git-Purpur-1057]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1057]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
 in 'string', line 6, column 1:
    sql-driver-class-name:"default"
    ^
could not find expected ':'
 in 'string', line 7, column 1:
    
    ^ 

        at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:463) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:278) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.16.5.jar:git-Purpur-1057]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.5.jar:git-Purpur-1057]
        ... 20 more

**Comment by Govindass** [comment] 2021-04-19 12:39
hmm I thought I've already fixed this, maybe I forgot to release jar, what's your skript-db version?

**Comment by Govindass** [comment] 2021-04-19 13:59
I have re-checked the history of commits, this was fixed in 1.2.1, please reset config and update to it

**Comment by toonystank** [comment] 2021-04-22 12:00
already using the latest version 1.2.1

**Comment by toonystank** [comment] 2021-04-22 12:04
> [12:03:41 ERROR]: Cannot load plugins/skript-db/config.yml
> org.bukkit.configuration.InvalidConfigurationException: while scanning a simple key
>  in 'string', line 6, column 1:
>     sql-driver-class-name:"default"
>     ^
> could not find expected ':'
>  in 'string', line 7, column 1:
>     
>     ^
> 
Same. I been using this version from start

**Comment by Govindass** [comment] 2021-04-22 12:07
interesting... for now you can add a space between : and "default" to fix it

**Comment by toonystank** [comment] 2021-04-22 12:21
Ya no error now

**Comment by Govindass** [comment] 2021-04-30 10:12
I have tested and was able to reproduce the problem, looks like I have accidently uploaded a older .jar file in last release :/ I will fix it once I am able to build a newer jar (I have reinstalled my OS and been having issues with getting it to build correctly)

**Comment by Govindass** [comment] 2021-05-12 10:30
should be fixed for the final time now

**Closed by Govindass** 2021-05-12 10:30 UTC
